export default function PointyPattern() {
    return (
        <svg
            className="absolute inset-0 h-full w-full"
            xmlns="http://www.w3.org/2000/svg"
        >
            <defs>
                <pattern
                    id="pointy-pattern"
                    x="0"
                    y="0"
                    width="40"
                    height="40"
                    patternUnits="userSpaceOnUse"
                >
                    {/* Main dots */}
                    <circle
                        cx="20"
                        cy="20"
                        r="1.5"
                        fill="currentColor"
                        opacity="0.15"
                    />
                    <circle
                        cx="0"
                        cy="0"
                        r="1"
                        fill="currentColor"
                        opacity="0.1"
                    />
                    <circle
                        cx="40"
                        cy="0"
                        r="1"
                        fill="currentColor"
                        opacity="0.1"
                    />
                    <circle
                        cx="0"
                        cy="40"
                        r="1"
                        fill="currentColor"
                        opacity="0.1"
                    />
                    <circle
                        cx="40"
                        cy="40"
                        r="1"
                        fill="currentColor"
                        opacity="0.1"
                    />

                    {/* Accent dots */}
                    <circle
                        cx="10"
                        cy="10"
                        r="0.8"
                        fill="currentColor"
                        opacity="0.08"
                    />
                    <circle
                        cx="30"
                        cy="30"
                        r="0.8"
                        fill="currentColor"
                        opacity="0.08"
                    />
                    <circle
                        cx="30"
                        cy="10"
                        r="0.6"
                        fill="currentColor"
                        opacity="0.06"
                    />
                    <circle
                        cx="10"
                        cy="30"
                        r="0.6"
                        fill="currentColor"
                        opacity="0.06"
                    />
                </pattern>
            </defs>
            <rect
                width="100%"
                height="100%"
                fill="url(#pointy-pattern)"
                className="text-brand"
            />
        </svg>
    );
}
